print("welcome to the tip calculator")
bill = float(input("what was the total bill? $ "))
tip = int(input("How much tip would you like to give ? 10 12 or 15 "))
numberOfMembers = int(input("How many people to split the bill? "))
print(f"Each person has to pay {(bill / numberOfMembers) * (tip / 100):.2f}")